# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fs2013.github.io/fafs_hello/"

git_url = "https://github.com/fs2013/fafs_hello/tree/First Branch/"

def custom_doc_links(name): return None
